VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Encomenda"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

'Class Encomenda


Public id As String
Public vendedor As String
Public cliente As String
Public data As String
Public valorTotal As Double
Public estado As String
Public documento As String

